### ISSUE TITLE
Final Capstone 

### ISSUE THREAD

**Issue by redwing555** [redwing555/final-capstone-frontend#8]
- The Group consists of four members: 

- @see-why 
- @Lordkaito 
- @redwing555 
- @leolpaz 
- [Front End Kanban board ](https://github.com/redwing555/final-capstone-frontend/projects/1)
- [Back End Kanban board ](https://github.com/Lordkaito/final-capstone-backend/projects/1)
### FrontEnd Kanban : 
![kanban board screenshot frontend](https://user-images.githubusercontent.com/75939922/154284589-84507a90-e972-435d-b50d-5f659255ac34.png)

### BackEnd Kanban : 
![Captura de pantalla 2022-02-16 152439](https://user-images.githubusercontent.com/75939922/154285321-34ae9394-876a-46c3-b42a-cb27dabbbf6e.jpg)

**Comment by MuriloRoque** [comment]
Hi @redwing555, @see-why, @Lordkaito, @leolpaz, 

In my opinion, your project is complete!

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
